/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.16
 * Generated at: 2018-08-06 02:01:15 UTC
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.sql.*;
import javax.sql.*;

public final class DetailFilter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.List<java.lang.String> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.List<java.lang.String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en-US\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"it student window, IT Student Window, IT STUDENT WINDOW, Invest in myanmar, finding fund\"/>\r\n");
      out.write("\t<link rel=\"Shortcut icon\" href=\"logo.png\" type=\"image/png\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"CSS/home.css\" />\r\n");
      out.write("\t<title></title>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
 
	int sessionCount=9;
int n=1;
int temp=0;

ArrayList<String> str=null;
	for(int i=0;i<sessionCount;i++){
		String btn="btn"+n;
		btn=request.getParameter("btnDetail"+n);
		
		if(!btn.equals("null") || !btn.equals("")){
			temp=n;break;
		}
		n++;
	}
	
//	out.println(str.get(temp));
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("\t<div class=\"messagebox\"> \r\n");
      out.write("\t\t<div class=\"messageimage\"><img src=\"Image/logo.png\" alt=\"Message Box\" width=\"40px\" height=\"40px\" /></div>\r\n");
      out.write("\t\t<div class=\"message\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t<div class=\"header\" id=\"myheader\"> \r\n");
      out.write("<!---------------------------------------------------------------logo and title----------------------------------------------------------->\r\n");
      out.write("\t\t<div class=\"head\"> \r\n");
      out.write("\t\t\t<div class=\"logo\"> <img src=\"Image/logo.png\" alt=\"it students window\" width=\"50px\" height=\"50px\"/></div>\r\n");
      out.write("\t\t\t<div class=\"title\"><h1><span class=\"change\">IT STUDENTS</span> WINDOW</h1> </div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"signin\"> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li onclick=\"document.getElementById('signupfilter').style.display='block'\" ><img src=\"Image/signin.png\" alt=\"gmg\"  width=\"25px\" height=\"25px\" class=\"signinImg\"><span class=\"signinspan\">SignIn</li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"loginfilter\" id=\"signupfilter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span onclick=\"document.getElementById('signupfilter').style.display='none'\" class=\"close\" title=\"Close Modal\">&#10006;</span>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"signuptype\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Creator SignIn\" onclick=\"studentSignUp()\" id=\"studnetSignUp\" class=\"login\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Investor SignIn\" onclick=\"investorSignUp()\" id=\"investorSignUp\" class=\"login\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Member SignIn\" onclick=\"memberSignUp()\" id=\"memberSignUp\" class=\"login\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"sign\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"sign\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"sign\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t          \r\n");
      out.write("\t\t\t\t\t\t\t\t<li onclick=\"document.getElementById('loginfilter').style.display='block'\"><img src=\"Image/signin.png\" alt=\"gmg\"  width=\"25px\" height=\"25px\" class=\"signinImg\"><span class=\"signinspan\">Login</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t    <div class=\"loginfilter\" id=\"loginfilter\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<span onclick=\"document.getElementById('loginfilter').style.display='none'\" class=\"close\" title=\"Close Modal\">&#10006;</span>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"logintype\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Creator Login\" onclick=\"studentLogin()\" id=\"studnetlogin\" class=\"login\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Investor Login\" onclick=\"investorLogin()\" id=\"investorLogin\" class=\"login\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Member Login\" onclick=\"memberLogin()\" id=\"memberLogin\" class=\"login\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"send\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"send\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"send\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("<!------------------------------------------------------------------navigation bar -------------------------------------------------------->\r\n");
      out.write("\t\t<div class=\"sub\"> \r\n");
      out.write("\t\t\t<div class=\"nav\"> \r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"home.html\"><img src=\"Image/home.png\" alt=\"Home\" ></img></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Html/Posts.jsp\"><img src=\"Image/post.png\" alt=\"Posts\"></img></a></li>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Html/HowItWork.html\" ><img src=\"Image/HowItWork.png\" alt=\"How It Work\" ></img></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Html/Guide.html\"><img src=\"Image/guide.png\" alt=\"Guide\"  ></img></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Html/member.jsp\"><img src=\"Image/members.png\" alt=\"Members List\"  ></img></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Html/About.html\"><img src=\"Image/aboutus.png\" alt=\"About Us\"  ></img> </a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!--------------------------------------------------------------Body------------------------------------------------------------>\r\n");
      out.write("\t<div class=\"body\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"filt\">Filter By:</div>\r\n");
      out.write("\t<div class=\"filterby\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li onclick=\"AllfilterP()\" class=\"Projectdown\" ><span id=\"changeallP\" onclick=\"tempshowP()\">Project Type &Delta;</span></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li onclick=\"AllfilterC()\" class=\"Projectdown\" ><span id=\"changeallC\" onclick=\"tempshowC()\">City &Delta;</span></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li onclick=\"AllfilterA()\" class=\"Projectdown\" ><span id=\"changeallA\" onclick=\"tempshowA()\">Invest Amount &Delta;</span></li>   \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li onclick=\"Allfilter()\" class=\"down\"><span id=\"changeall\" onclick=\"tempshow()\"> Filter &and; </span></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</ul>    \r\n");
      out.write("\t\t<div class=\"clear\"></div>\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"filter.jsp\" method=\"post\" class=\"filterform\" id=\"AllfilterP\">\r\n");
      out.write("\t\t<section>\r\n");
      out.write("\t\t\t<article ><input type=\"checkbox\" value=\"web\" name=\"type\"/>&nbsp;Web Technology</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"application\" name=\"type\"/>&nbsp;Application</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"hardware\" name=\"type\"/>&nbsp;Hardware</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"game\" name=\"type\"/>&nbsp;Game</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"other\" name=\"type\"/>&nbsp;Other</article>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Filter\" name=\"btnproject\" class=\"filterbtn\"/>\r\n");
      out.write("\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<form action=\"filter.jsp\" method=\"post\" class=\"filterform\" id=\"AllfilterC\">\t\r\n");
      out.write("\t\t<section class=\"filterScroll\">\r\n");
      out.write("\t\t\t<article ><input type=\"checkbox\" value=\"yangon\" name=\"city\"/>&nbsp;Yangon</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"mandalay\" name=\"city\"/>&nbsp;Mandalay</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"meiktila\" name=\"city\"/>&nbsp;Meiktila</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"naypyitaw\" name=\"city\"/>&nbsp;Myitgyina</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"other\" name=\"city\"/>&nbsp;Other</article>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Filter\" name=\"btncity\" class=\"filterbtn\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("    <form action=\"filter.jsp\" method=\"post\" class=\"filterform\" id=\"AllfilterA\">\t\r\n");
      out.write("\t\t<section class=\"filterScroll\">\r\n");
      out.write("\t\t\t<article ><input type=\"checkbox\" value=\"5000000\" name=\"city\"/>&nbsp;5,000,000</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"10000000\" name=\"city\"/>&nbsp;10,000,000</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"15000000\" name=\"city\"/>&nbsp;15,000,000</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"30000000\" name=\"city\"/>&nbsp;30,000,000</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"above\" name=\"city\"/>&nbsp;above</article>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Filter\" name=\"btnamount\" class=\"filterbtn\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<form action=\"filter.jsp\" method=\"post\" class=\"filterform\" id=\"Allfilter\">\r\n");
      out.write("\t\t<section>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"web\" name=\"type\"/>&nbsp;Web Technology</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"application\" name=\"type\"/>&nbsp;Application</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"hardware\" name=\"type\"/>&nbsp;Hardware</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"hardware\" name=\"type\"/>&nbsp;Game</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"typeother\" name=\"type\"/>&nbsp;Other</article>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<section class=\"filterScroll\">\r\n");
      out.write("\t\t\t<article ><input type=\"checkbox\" value=\"yangon\" name=\"city\"/>&nbsp;Yangon</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"mandalay\" name=\"city\"/>&nbsp;Mandalay</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"meiktila\" name=\"city\"/>&nbsp;Meiktila</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"naypyitaw\" name=\"city\"/>&nbsp;Myitgyina</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"cityother\" name=\"city\"/>&nbsp;Other</article>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<section class=\"filterScroll\">\r\n");
      out.write("\t\t\t<article ><input type=\"checkbox\" value=\"one\" name=\"city\"/>&nbsp;5,000,000</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"two\" name=\"city\"/>&nbsp;10,000,000</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"three\" name=\"city\"/>&nbsp;15,000,000</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"four\" name=\"city\"/>&nbsp;30,000,000</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"amountother\" name=\"city\"/>&nbsp;above</article>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Filter\" name=\"btnfilter\" class=\"filterbtn\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<div class =\"overparent\">\r\n");
      out.write("\t<div class=\"overchild\">\r\n");
      out.write("\t\t<form action=\"DetailFilter.jsp\" action=\"post\" class=\"postNav\">\r\n");
      out.write("\t\t\t<button name=\"btnAll\" class=\"btndetail\">All</button>\r\n");
      out.write("\t\t\t<button name=\"btnEducation\" class=\"btndetail\">Education</button>\r\n");
      out.write("\t\t\t<button name=\"btnHealth\" class=\"btndetail\">Health</button>\r\n");
      out.write("\t\t\t<button name=\"btnAgriculture\" class=\"btndetail\">Agriculture</button>\r\n");
      out.write("\t\t\t<button name=\"btnFood\" class=\"btndetail\">Food</button>\r\n");
      out.write("\t\t\t<button name=\"btnTravel\" class=\"btndetail\">Travel</button>\r\n");
      out.write("\t\t\t<button name=\"btnAgency\" class=\"btndetail\">Agency</button>\r\n");
      out.write("\t\t\t<button name=\"btnShopping\" class=\"btndetail\">Shopping</button>\r\n");
      out.write("\t\t\t<button name=\"btnEntertainment\" class=\"btndetail\">Entertainment</button>\r\n");
      out.write("\t\t\t<button name=\"btnMedia\" class=\"btndetail\">Media</button>\r\n");
      out.write("\t\t\t<button name=\"btnMachinery\" class=\"btndetail\">Machinery</button>\r\n");
      out.write("\t\t\t<button name=\"btnController\" class=\"btndetail\">Controller Device</button>\r\n");
      out.write("\t\t\t<button name=\"btnNetworking\" class=\"btndetail\">Networking</button>\r\n");
      out.write("\t\t\t<button name=\"btnOther\" class=\"btndetail\">Other</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("\t\r\n");
      out.write("<!----------------------------------------------------Ending Body------------------------------------------------>\r\n");

	
	
	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"post\"> \r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"leftPost\"> \r\n");
      out.write("\t\t\t<div class=\"firstPost\">\r\n");
      out.write("\t\t\t\t<div class=\"top\">               \t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"posttitle\">IT STUDENTS WINDOW</div>\r\n");
      out.write("\t\t\t\t\t <div class=\"viewcountpost\">\r\n");
      out.write("\t\t\t\t\t \t  <img src=\"Image/viewcount1.png\" alt=\"Twitter\" width=\"20px\" height=\"12px\" class=\"\" />\r\n");
      out.write("                  \t\t <span class=\"count\">2</span>\r\n");
      out.write("                  \t </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"middle\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"factmainpost\">Group Name : </span><span class=\"factdetailpost\">IT STUDETNS WINDOW</span><br/>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"factmainpost\">Social Impact : </span><span class=\"factdetailpost\"></span><br/>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"factmainpost\">Competitors : </span><span class=\"factdetailpost\">No competition</span><br/>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"factmainpost\">Competiton Advantage : </span><span class=\"factdetailpost\">3 stage</span><br/>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"factmainpost\">Required Capital  Amount : </span><span class=\"factdetailpost\">200,000</span><br/>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"factmainpost\">Project Type : </span><span class=\"factdetailpost\">Application</span><br/>\t<br/>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"Detail Info ->\" name=\"btndetail\"  class=\"topbtn\" onclick=\"document.getElementById('detailpost').style.display='block'\"/><br/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("<!----------------------------------------->\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"rightPost\"> \r\n");
      out.write("\t\t\r\n");
int count=1; 
      out.write("\r\n");
      out.write("\t\t<form class=\"group\" action=\"DetailFilter.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\r\n");

String btndetail="btnDetail"+count;
count++;

      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"grouptitle1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"posttitle1\">IT STUDETNS WINDOW</div>\r\n");
      out.write("                   <div class=\"viewcount\">\r\n");
      out.write("\t\t\t\t\t \t<img src=\"Image/viewcount1.png\" alt=\"View Count\" width=\"17px\" height=\"10px\" />\r\n");
      out.write("                  \t\t<span class=\"countright\">1</span>\r\n");
      out.write("                  \t</div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t    \t\t<img src=\"Image/app1.jpg\" alt=\"Circle Image\" width=\"120px\" height=\"120px\" class=\"groupimg\"/><br />\r\n");
      out.write("\t\t\t    \t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<label for=\"Group Name\" class=\"gplbl\">Group Name:&nbsp;</label><span>MovingStars</span> <br />\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"Detail Info ->\" name=\"");
      out.print( btndetail );
      out.write("\" onclick=\"document.getElementById('detailpost').style.display='block'\"\" class=\"groupdetail\" />\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!----------------------------------------------------------------footer------------------------------------------------------------------>\r\n");
      out.write("\t\t<div class=\"footer\"> \r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<center><p class=\"copyright\"><small>copyright &copy; 2018; All right reserved.</small></p></center>\r\n");
      out.write("\t\t\t\t<div class=\"foot\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"help.html\">Help</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"termOfUse.html\">Term of Use</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"privacyPolicy.html\">Privacy Policy</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li onclick=\"\" ><a href=\"feedback.html\">Feedback</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<div id=\"feed\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"contactFrame\"> \r\n");
      out.write("\t\t\t\t\t<p class=\"contactFrame\">Contact us:&nbsp;&nbsp;www.itstudentwindow.com<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9742;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"tel:09265427138\"> 09265427138</a></p>\r\n");
      out.write("\t\t\t\t\t<div class=\"contactImage\"> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.facebook.com/profile.php?id=100012164478367\"> \r\n");
      out.write("\t\t\t\t\t\t<img src=\"Image/facebook.jpg\" alt=\"Facebook\" width=\"20px\" height=\"20px\" /></a>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"Image/twitter.jpg\" alt=\"Twitter\" width=\"20px\" height=\"20px\"/>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"Image/linkedin.jpg\" alt=\"LinkedIn\" width=\"20px\" height=\"20px\"/>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"Image/gmail.png\" alt=\"Gmail\" width=\"20px\" height=\"20px\" />\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!---------------------------------------------------------------------------------------popular app-------------------------------------------------------->\r\n");
      out.write("\t<div class=\"popularapp\"> \r\n");
      out.write("\t\t<div class=\"popular\"> \r\n");
      out.write("\t\t\t<div class=\"popu\"><img src=\"Image/logo.png\" alt=\"First Popular\" width=\"35px\" height=\"35px\" class=\"pop\"/></div>\r\n");
      out.write("\t\t\t<div class=\"popu\"><img src=\"Image/logo.png\" alt=\"Second Popular\" width=\"35px\" height=\"35px\" class=\"pop\"/></div>\r\n");
      out.write("\t\t\t<div  class=\"popu\"><img src=\"Image/logo.png\" alt=\"Third Popular\" width=\"35px\" height=\"35px\" class=\"pop\"/></div>\r\n");
      out.write("\t\t\t<div  class=\"popu\"><img src=\"Image/logo.png\" alt=\"Fouth Popular\" width=\"35px\" height=\"35px\" class=\"pop\"/></div>\r\n");
      out.write("\t\t\t<div class=\"popu\"><img src=\"Image/logo.png\" alt=\"Fifth Popular\" width=\"35px\" height=\"35px\" class=\"pop\"/></div>\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t<div class=\"popularfull\"><img src=\"Image/logo.png\" alt=\"Popular\" width=\"150px\" height=\"150px\" class=\"pop\"/> \r\n");
      out.write("\t\t\t<p>IT STUDENTS WINDOW</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\" src=\"JS/home.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
