/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.16
 * Generated at: 2018-08-06 01:17:08 UTC
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;

public final class filter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.List<java.lang.String> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.List<java.lang.String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en-US\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"keywords\" content=\"it student window, IT Student Window, IT STUDENT WINDOW, Invest in myanmar, finding fund\"/>\r\n");
      out.write("\t<link rel=\"Shortcut icon\" href=\"logo.png\" type=\"image/png\"/>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"CSS/home.css\" />\r\n");
      out.write("\t<title></title>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"messagebox\"> \r\n");
      out.write("\t\t<div class=\"messageimage\" onclick=\"showmsg()\" ><img src=\"Image/message.png\" alt=\" \" width=\"35px\" height=\"33px\" /></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"message\" id=\"msg\">\r\n");
      out.write("\t\t\t<div class=\"it\">\r\n");
      out.write("\t\t\t\t<img src=\"Image/logo.png\" alt=\"logo\" width=\"25px\" height=\"25px\" class=\"lmsg\">\r\n");
      out.write("\t\t\t\t<span class=\"itsw\">IT STUDENTS WINDOW</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"msg\">\r\n");
      out.write("\t\t\t\t<div class=\"r\"><span class=\"receiver\">Hello! May I help you!</span></div>\r\n");
      out.write("\t\t\t\t<div class=\"s\"><span class=\"sender\">Hello!</span></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<div class=\"sendmsg\">\r\n");
      out.write("\t\t\t\t<input type=\"text\"  id=\"msg\" name=\"message\" placeholder=\"Ask you konw.?\" class=\"hintmsg\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"Send\" class=\"msgbtn\" id=\"sendmsg\" onclick=\"sendmsg()\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<div class=\"header\" id=\"myheader\"> \r\n");
      out.write("\r\n");
      out.write("<!---------------------------------------------------------------logo OR title----------------------------------------------------------->\r\n");
      out.write("\t\t<div class=\"head\"> \r\n");
      out.write("\t\t\t<div class=\"logo\"> <img src=\"Image/logo.png\" alt=\"it students window\" width=\"50px\" height=\"50px\"/></div>\r\n");
      out.write("\t\t\t<div class=\"title\"><h1><span class=\"change\">IT STUDENTS</span> WINDOW</h1> </div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"signin\"> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li onclick=\"document.getElementById('signupfilter').style.display='block'\" ><img src=\"Image/signin.png\" alt=\"gmg\"  width=\"25px\" height=\"25px\" class=\"signinImg\"><span class=\"signinspan\">SignIn</li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"loginfilter\" id=\"signupfilter\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span onclick=\"document.getElementById('signupfilter').style.display='none'\" class=\"close\" title=\"Close Modal\">&#10006;</span>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"signuptype\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Creator SignIn\" onclick=\"studentSignUp()\" id=\"studnetSignUp\" class=\"login\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Investor SignIn\" onclick=\"investorSignUp()\" id=\"investorSignUp\" class=\"login\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Member SignIn\" onclick=\"memberSignUp()\" id=\"memberSignUp\" class=\"login\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"sign\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"sign\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"sign\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t          \r\n");
      out.write("\t\t\t\t\t\t\t\t<li onclick=\"document.getElementById('loginfilter').style.display='block'\"><img src=\"Image/signin.png\" alt=\"gmg\"  width=\"25px\" height=\"25px\" class=\"signinImg\"><span class=\"signinspan\">Login</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t    <div class=\"loginfilter\" id=\"loginfilter\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<span onclick=\"document.getElementById('loginfilter').style.display='none'\" class=\"close\" title=\"Close Modal\">&#10006;</span>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"logintype\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Creator Login\" onclick=\"studentLogin()\" id=\"studnetlogin\" class=\"login\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Investor Login\" onclick=\"investorLogin()\" id=\"investorLogin\" class=\"login\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"Member Login\" onclick=\"memberLogin()\" id=\"memberLogin\" class=\"login\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"send\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"send\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"send\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("<!------------------------------------------------------------------navigation bar -------------------------------------------------------->\r\n");
      out.write("\t\t<div class=\"sub\"> \r\n");
      out.write("\t\t\t<div class=\"nav\"> \r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"home.html\"><img src=\"Image/home.png\" alt=\"Home\" ></img></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Html/Posts.jsp\"><img src=\"Image/post.png\" alt=\"Posts\"></img></a></li>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Html/HowItWork.html\" ><img src=\"Image/HowItWork.png\" alt=\"How It Work\" ></img></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Html/Guide.html\"><img src=\"Image/guide.png\" alt=\"Guide\"  ></img></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Html/member.jsp\"><img src=\"Image/members.png\" alt=\"Members List\"  ></img></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"Html/About.html\"><img src=\"Image/aboutus.png\" alt=\"About Us\"  ></img> </a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!--------------------------------------------------------------Body------------------------------------------------------------>\r\n");
      out.write("\t<div class=\"body\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"filt\">Filter By:</div>\r\n");
      out.write("\t<div class=\"filterby\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li onclick=\"AllfilterP()\" class=\"Projectdown\" ><span id=\"changeallP\" onclick=\"tempshowP()\">Project Type &Delta;</span></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li onclick=\"AllfilterC()\" class=\"Projectdown\" ><span id=\"changeallC\" onclick=\"tempshowC()\">City &Delta;</span></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li onclick=\"AllfilterA()\" class=\"Projectdown\" ><span id=\"changeallA\" onclick=\"tempshowA()\">Invest Amount &Delta;</span></li>   \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<li onclick=\"Allfilter()\" class=\"down\"><span id=\"changeall\" onclick=\"tempshow()\"> Filter &OR; </span></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</ul>    \r\n");
      out.write("\t\t<div class=\"clear\"></div>\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"filter.jsp\" method=\"post\" class=\"filterform\" id=\"AllfilterP\">\r\n");
      out.write("\t\t<section>\r\n");
      out.write("\t\t\t<article ><input type=\"checkbox\" value=\"Website\" name=\"type\"/>&nbsp;Web Technology</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Application\" name=\"type\"/>&nbsp;Application</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Hardware\" name=\"type\"/>&nbsp;Hardware</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Platform\" name=\"type\"/>&nbsp;Platform</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Game\" name=\"type\"/>&nbsp;Game</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Other\" name=\"type\"/>&nbsp;Other</article>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Filter\" name=\"btnproject\" class=\"filterbtn\"/>\r\n");
      out.write("\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<form action=\"filter.jsp\" method=\"post\" class=\"filterform\" id=\"AllfilterC\">\t\r\n");
      out.write("\t\t<section class=\"filterScroll\">\r\n");
      out.write("\t\t\t<article ><input type=\"checkbox\" value=\"Yangon\" name=\"city\"/>&nbsp;Yangon</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"MORalay\" name=\"city\"/>&nbsp;MORalay</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Meiktila\" name=\"city\"/>&nbsp;Meiktila</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Myitkyina\" name=\"city\"/>&nbsp;Myitgyina</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Taunggyi\" name=\"city\"/>&nbsp;Taunggyi</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Other\" name=\"city\"/>&nbsp;Other</article>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Filter\" name=\"btncity\" class=\"filterbtn\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("    <form action=\"filter.jsp\" method=\"post\" class=\"filterform\" id=\"AllfilterA\">\t\r\n");
      out.write("\t\t<section class=\"filterScroll\">\r\n");
      out.write("\t\t\t<article ><input type=\"checkbox\" value=\"Five\" name=\"city\"/>&nbsp;5,000,000</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Ten\" name=\"city\"/>&nbsp;10,000,000</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Fifteen\" name=\"city\"/>&nbsp;15,000,000</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Thirty\" name=\"city\"/>&nbsp;30,000,000</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Above\" name=\"city\"/>&nbsp;above</article>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Filter\" name=\"btnamount\" class=\"filterbtn\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<form action=\"filter.jsp\" method=\"post\" class=\"filterform\" id=\"Allfilter\">\r\n");
      out.write("\t\t<section>\r\n");
      out.write("\t\t\t<article ><input type=\"checkbox\" value=\"Website\" name=\"type\"/>&nbsp;Web Technology</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Application\" name=\"type\"/>&nbsp;Application</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Hardware\" name=\"type\"/>&nbsp;Hardware</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Platform\" name=\"type\"/>&nbsp;Platform</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Game\" name=\"type\"/>&nbsp;Game</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Other\" name=\"type\"/>&nbsp;Other</article>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<section class=\"filterScroll\">\r\n");
      out.write("\t\t\t<article ><input type=\"checkbox\" value=\"Yangon\" name=\"city\"/>&nbsp;Yangon</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"MORalay\" name=\"city\"/>&nbsp;MORalay</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Meiktila\" name=\"city\"/>&nbsp;Meiktila</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Myitkyina\" name=\"city\"/>&nbsp;Myitgyina</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Taunggyi\" name=\"city\"/>&nbsp;Taunggyi</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Other\" name=\"city\"/>&nbsp;Other</article>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<section class=\"filterScroll\">\r\n");
      out.write("\t\t\t<article ><input type=\"checkbox\" value=\"Five\" name=\"city\"/>&nbsp;5,000,000</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Ten\" name=\"city\"/>&nbsp;10,000,000</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Fifteen\" name=\"city\"/>&nbsp;15,000,000</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Thirty\" name=\"city\"/>&nbsp;30,000,000</article>\r\n");
      out.write("\t\t\t<article><input type=\"checkbox\" value=\"Above\" name=\"city\"/>&nbsp;above</article>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Filter\" name=\"btnfilter\" class=\"filterbtn\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<div class =\"overparent\">\r\n");
      out.write("\t<div class=\"overchild\">\r\n");
      out.write("\t\t<form action=\"DetailFilter.jsp\" action=\"post\" class=\"postNav\">\r\n");
      out.write("\t\t\t<button name=\"btnAll\" class=\"btndetail\">All</button>\r\n");
      out.write("\t\t\t<button name=\"btnEducation\" class=\"btndetail\">Education</button>\r\n");
      out.write("\t\t\t<button name=\"btnHealth\" class=\"btndetail\">Health</button>\r\n");
      out.write("\t\t\t<button name=\"btnAgriculture\" class=\"btndetail\">Agriculture</button>\r\n");
      out.write("\t\t\t<button name=\"btnFood\" class=\"btndetail\">Food</button>\r\n");
      out.write("\t\t\t<button name=\"btnTravel\" class=\"btndetail\">Travel</button>\r\n");
      out.write("\t\t\t<button name=\"btnAgency\" class=\"btndetail\">Agency</button>\r\n");
      out.write("\t\t\t<button name=\"btnShopping\" class=\"btndetail\">Shopping</button>\r\n");
      out.write("\t\t\t<button name=\"btnEntertainment\" class=\"btndetail\">Entertainment</button>\r\n");
      out.write("\t\t\t<button name=\"btnMedia\" class=\"btndetail\">Media</button>\r\n");
      out.write("\t\t\t<button name=\"btnMachinery\" class=\"btndetail\">Machinery</button>\r\n");
      out.write("\t\t\t<button name=\"btnController\" class=\"btndetail\">Controller Device</button>\r\n");
      out.write("\t\t\t<button name=\"btnNetworking\" class=\"btndetail\">Networking</button>\r\n");
      out.write("\t\t\t<button name=\"btnOther\" class=\"btndetail\">Other</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("\t\r\n");
      out.write("<!----------------------------------------------------Ending Body------------------------------------------------>\r\n");
      out.write("\t");

	Class.forName("com.mysql.jdbc.Driver");
	java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ITStudentWindow","root","root");
	
	String btnfilter=null,btnproject=null,btnamount=null,btncity=null;
	
	btnfilter=request.getParameter("btnfilter");
	btnproject=request.getParameter("btnproject");
	btncity=request.getParameter("btncity");
	btnamount=request.getParameter("btnamount");
	
	String[] projectArr,amountArr,cityArr,projectAllArr,cityAllArr,amountAllArr;
	
	Statement st=con.createStatement();
	ResultSet rs=null,rs1=null;

	String condition="";
	try{

	if(btnfilter!=null){
		condition="";
		
		projectAllArr=request.getParameterValues("projectAll");
		cityAllArr=request.getParameterValues("cityAll");
		amountAllArr=request.getParameterValues("amountAll");
		
		for(int i=0;i< projectAllArr.length;i++){
			condition+="ProjectType = \'"+projectAllArr[i]+"\' OR";
			
		}	
		
		for(int i=0;i< cityAllArr.length;i++){
			condition+="City = \'"+cityAllArr[i]+"\' OR";
		}	
		
		for(int i=0;i< amountAllArr.length;i++){
			condition+="InvestAmount = \'"+amountAllArr[i]+"\' OR";
		}	
		
		rs=st.executeQuery("select ProjectTitle,GroupName,CapitalAmount,SocialImpact,Competitors,ProjectType,CompetitiveAdvCount,MAX(ViewCount) from Project where "+condition.subSequence(0, condition.length()-4));
	
	}else if(btnproject!=null){
		condition="";
		projectArr=request.getParameterValues("type");

		for(int i=0;i< projectArr.length;i++){
			condition+="ProjectType = \'"+projectArr[i]+"\' OR ";
		}	
		
		rs=st.executeQuery("select ProjectTitle,GroupName,CapitalAmount,SocialImpact,Competitors,ProjectType,CompetitiveAdvCount,MAX(ViewCount) from Project where "+condition.subSequence(0, condition.length()-4));
	
	}else if(btnamount!=null){
		condition="";
		
		amountArr=request.getParameterValues("amount");
	
		for(int i=0;i<amountArr.length;i++){
			condition+="InvestAmount=\'"+amountArr[i]+"\' OR";
		}
		
		
		rs=st.executeQuery("select ProjectTitle,GroupName,CapitalAmount,SocialImpact,Competitors,ProjectType,CompetitiveAdvCount,MAX(ViewCount) from Project where "+condition.subSequence(0, condition.length()-4));
	
		
	}else if(btncity!=null){
		condition="";
		
		cityArr=request.getParameterValues("city");
		
		for(int i=0;i<cityArr.length;i++){
			condition+="City=\'"+cityArr[i]+"\' OR";
		}
		//out.println("Condition "+condition);
		rs=st.executeQuery("select ProjectTitle,GroupName,CapitalAmount,SocialImpact,Competitors,ProjectType,CompetitiveAdvCount,MAX(ViewCount) from Project where "+condition.subSequence(0, condition.length()-4));
		
	}
	
	//-------------------------------------------------------------------------
	
		
		//st.executeUpdate("delete from view");
		
	String title,name,social,type,competitor;
int amount,competitiveCount,view;

	while(rs.next()){
		title=rs.getString(1);
		name=rs.getString(2);
		amount=rs.getInt(3);
		social=rs.getString(4);
		competitor=rs.getString(5);
		type=rs.getString(6);
		competitiveCount=rs.getInt(7);
		view=rs.getInt(8);
		
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"post\"> \r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"leftPost\"> \r\n");
      out.write("\t\t\t<div class=\"firstPost\">\r\n");
      out.write("\t\t\t\t<div class=\"top\">               \t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"posttitle\">");
      out.print( title );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t <div class=\"viewcountpost\">\r\n");
      out.write("\t\t\t\t\t \t  <img src=\"Image/viewcount1.png\" alt=\"Twitter\" width=\"20px\" height=\"12px\" class=\"\" />\r\n");
      out.write("                  \t\t <span class=\"count\">");
      out.print( view );
      out.write("</span>\r\n");
      out.write("                  \t </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"middle\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"factmainpost\">Group Name : </span><span class=\"factdetailpost\">");
      out.print( name );
      out.write("</span><br/>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"factmainpost\">Social Impact : </span><span class=\"factdetailpost\">");
      out.print(social );
      out.write("</span><br/>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"factmainpost\">Competitors : </span><span class=\"factdetailpost\">");
      out.print(competitor );
      out.write("</span><br/>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"factmainpost\">Competitive Advantage : </span><span class=\"factdetailpost\">");
      out.print(competitiveCount );
      out.write("stage</span><br/>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"factmainpost\">Required Capital  Amount : </span><span class=\"factdetailpost\">");
      out.print(amount );
      out.write("</span><br/>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"factmainpost\">Project Type : </span><span class=\"factdetailpost\">");
      out.print(amount );
      out.write(" </span><br/>\t<br/>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"Detail Info ->\" name=\"btndetail\"  class=\"topbtn\" onclick=\"document.getElementById('detailpost').style.display='block'\"/><br/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"detailpostfilter\" id=\"detailpost\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t<div class='postframe'>\r\n");
      out.write("\t\t\t\t\t<div id='invest'></div>\r\n");
      out.write("\t\t\t\t\t<div class='postform'>\r\n");
      out.write("\t\t\t\t\t\t<div class='topPost'>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class='postTitle'>");
      out.print(title );
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class='clear'></div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class='middlepost'>\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t <td class=\"factdetail\">Group Name :</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t <td class=\"fact1detail\">");
      out.print( name );
      out.write("</td> \r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"factdetail\">Social Impact : </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"fact1detail\">");
      out.print(social );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"factdetail\">Competitors : </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"fact1detail\">");
      out.print(competitor );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"factdetail\">Competitive Advantage : </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"fact1detail\">");
      out.print(competitiveCount );
      out.write(" stages</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"factdetail\">Required Capital Amount : </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"fact1detail\">$");
      out.print(amount );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class='bottomPost'>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t    <li class=\"like\"><a href=\"\">Like </a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class='commentPost' onclick=\"document.getElementById('commentTextbox').style.display='block'\">Comment</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class='investPost' onclick='invest()'><a href='Contact.html'>Invest</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class='scrollbar'>\r\n");
      out.write("\t\t\t\t\t\t<div class='commentBox'>\r\n");
      out.write("\t\t\t\t\t\t\t<div class='commentPeople'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class='commentLogo'><img src='Image/logo.png' alt='Circle Image' width='35px' height='35px'/></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class='commentName'>Aye Myat Myat Soe</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class='commenttext'>That is good.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class='commentTextbox' id='commentTextbox' >\r\n");
      out.write("\t\t\t\t\t<textarea name='commenttext' class='textbox' placeholder=\"Write a comment...\" >\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</textarea>\r\n");
      out.write("\t\t\t\t\t<span onclick=\"document.getElementById('signupfilter').style.display='none'\" class=\"close\" title=\"Close Modal\">&#10006;</span>\r\n");
      out.write("\t\t\t\t\t\t<input type='submit' value='Send' name='sendcom' class='sendcomment' />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class='clear'></div>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" onclick=\"document.getElementById('detailpost').style.display='none'\" value=\"Close\" class=\"hidebtn\"/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");

			} //end while
			
      out.write("\r\n");
      out.write("<!----------------------------------------->\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div class=\"rightPost\"> \r\n");
      out.write("\t\t");

		int n=1;
		String strclass="";
		rs1=st.executeQuery("select ProjectTitle,GroupName,CapitalAmount,SocialImpact,Competitors,ProjectType,CompetitiveAdvCount,ViewCount from Project where "+condition.subSequence(0, condition.length()-4));
		
		
		while(rs1.next()){
			title=rs1.getString(1);
			name=rs1.getString(2);
			amount=rs1.getInt(3);
			social=rs1.getString(4);
			competitor=rs1.getString(5);
			type=rs1.getString(6);
			competitiveCount=rs1.getInt(7);
			view=rs1.getInt(8);
			
			strclass="detailpost"+n;
			n++;
		 
      out.write("\r\n");
      out.write("\t<div class=\"group\">\r\n");
      out.write("\t\t\t\t<div class=\"grouptitle1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"posttitle1\">");
      out.print( title );
      out.write("</div>\r\n");
      out.write("                   <div class=\"viewcount\">\r\n");
      out.write("\t\t\t\t\t \t<img src=\"Image/viewcount1.png\" alt=\"View Count\" width=\"17px\" height=\"10px\" />\r\n");
      out.write("                  \t\t<span class=\"countright\">");
      out.print(view );
      out.write("</span>\r\n");
      out.write("                  \t</div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t   ");
if(type.equals("Application")){
      out.write("\r\n");
      out.write("\t\t\t    \t\t<img src=\"Image/app1.jpg\" alt=\"Circle Image\" width=\"120px\" height=\"120px\" class=\"groupimg\"/><br />\r\n");
      out.write("\t\t\t    ");
}else if(type.equals("Website")){ 
      out.write("  \r\n");
      out.write("\t\t\t    <img src=\"Image/app1.jpg\" alt=\"Circle Image\" width=\"120px\" height=\"120px\" class=\"groupimg\"/><br />\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    ");
}else if(type.equals("Hardware")){ 
      out.write("  \r\n");
      out.write("\t\t\t    <img src=\"Image/app1.jpg\" alt=\"Circle Image\" width=\"120px\" height=\"120px\" class=\"groupimg\"/><br />\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t    ");
}else if(type.equals("Game")){ 
      out.write("  \r\n");
      out.write("\t\t\t    <img src=\"Image/app1.jpg\" alt=\"Circle Image\" width=\"120px\" height=\"120px\" class=\"groupimg\"/><br />\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t\t");
}else if(type.equals("Other")){ 
      out.write("  \r\n");
      out.write("\t\t\t    <img src=\"Image/app1.jpg\" alt=\"Circle Image\" width=\"120px\" height=\"120px\" class=\"groupimg\"/><br />\r\n");
      out.write("\t\t\t    ");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t    <img src=\"Image/app1.jpg\" alt=\"Circle Image\" width=\"120px\" height=\"120px\" class=\"groupimg\"/><br />\r\n");
      out.write("\t\t\t\t    ");
} 
      out.write("\r\n");
      out.write("\t\t\t    \t<label for=\"Group Name\" class=\"gplbl\">Group Name:&nbsp;</label><span>");
      out.print(name );
      out.write("</span> <br />\r\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"Detail Info ->\" name=\"\" onclick=\"document.getElementById('");
      out.print(strclass );
      out.write("').style.display='block'\"\" class=\"groupdetail\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"detailpostfilter\" id=\"");
      out.print(strclass);
      out.write("\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t<div class='postframe'>\r\n");
      out.write("\t\t\t\t\t<div id='invest'></div>\r\n");
      out.write("\t\t\t\t\t<div class='postform'>\r\n");
      out.write("\t\t\t\t\t\t<div class='topPost'>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class='postTitle'>");
      out.print(title );
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class='clear'></div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class='middlepost'>\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t <td class=\"factdetail\">Group Name :</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t <td class=\"fact1detail\">");
      out.print( name );
      out.write("</td> \r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"factdetail\">Social Impact : </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"fact1detail\">");
      out.print(social );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"factdetail\">Competitors : </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"fact1detail\">");
      out.print(competitor );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"factdetail\">Competitive Advantage : </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"fact1detail\">");
      out.print(competitiveCount );
      out.write(" stages</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"factdetail\">Required Capital Amount : </td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"fact1detail\">$");
      out.print(amount );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class='bottomPost'>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t    <li class=\"like\"><a href=\"\">Like </a> </li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class='commentPost' onclick=\"document.getElementById('commentTextbox').style.display='block'\">Comment</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class='investPost' onclick='invest()'><a href='Contact.html'>Invest</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class='scrollbar'>\r\n");
      out.write("\t\t\t\t\t\t<div class='commentBox'>\r\n");
      out.write("\t\t\t\t\t\t\t<div class='commentPeople'>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class='commentLogo'><img src='Image/logo.png' alt='Circle Image' width='35px' height='35px'/></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class='commentName'>Aye Myat Myat Soe</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class='commenttext'>That is good.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class='commentTextbox' id='commentTextbox' >\r\n");
      out.write("\t\t\t\t\t<textarea name='commenttext' class='textbox' placeholder=\"Write a comment...\" >\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</textarea>\r\n");
      out.write("\t\t\t\t\t<span onclick=\"document.getElementById('signupfilter').style.display='none'\" class=\"close\" title=\"Close Modal\">&#10006;</span>\r\n");
      out.write("\t\t\t\t\t\t<input type='submit' value='Send' name='sendcom' class='sendcomment' />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class='clear'></div>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" onclick=\"document.getElementById('");
      out.print(strclass );
      out.write("').style.display='none'\" value=\"Close\" class=\"hidebtn\"/>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t");
 }//end while
		
		
		
      out.write("\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"clear\"></div>\r\n");
}catch(Exception e){
	out.println(condition.substring(0, condition.length()-4));
}
		
	con.close(); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("\t<!----------------------------------------------------------------footer------------------------------------------------------------------>\r\n");
      out.write("\t\t<div class=\"footer\"> \r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<center><p class=\"copyright\"><small>copyright &copy; 2018; All right reserved.</small></p></center>\r\n");
      out.write("\t\t\t\t<div class=\"foot\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"help.html\">Help</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"termOfUse.html\">Term of Use</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"privacyPolicy.html\">Privacy Policy</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"feedback.html\">Feedback</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<div id=\"feed\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"contactFrame\"> \r\n");
      out.write("\t\t\t\t\t<p class=\"contactFrame\">Contact us:&nbsp;&nbsp;www.itstudentwindow.com<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#9742;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"tel:09265427138\"> 09265427138</a></p>\r\n");
      out.write("\t\t\t\t\t<div class=\"contactImage\"> \r\n");
      out.write("\t\t\t\t\t\t<a href=\"https://www.facebook.com/profile.php?id=100012164478367\"> \r\n");
      out.write("\t\t\t\t\t\t<img src=\"Image/facebook.jpg\" alt=\"Facebook\" width=\"20px\" height=\"20px\" /></a>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"Image/twitter.jpg\" alt=\"Twitter\" width=\"20px\" height=\"20px\"/>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"Image/linkedin.jpg\" alt=\"LinkedIn\" width=\"20px\" height=\"20px\"/>\r\n");
      out.write("\t\t\t\t\t\t<img src=\"Image/gmail.png\" alt=\"Gmail\" width=\"20px\" height=\"20px\" />\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!---------------------------------------------------------------------------------------popular app-------------------------------------------------------->\r\n");
      out.write("\t<div class=\"popularcover\">\r\n");
      out.write("\t<div class=\"popularapp\"> \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"slideshow-container1\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"popularfive\" id=\"five\"> \r\n");
      out.write("\t\t\t\t\t\tTop 10 Popular App\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<div class=\"popularfull\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"mySlides2 fadeMsg\">\r\n");
      out.write("\t\t\t\t\t<img src=\"Image/logo.png\" alt=\"Popular\" width=\"150px\" height=\"150px\" class=\"pop\"/> \r\n");
      out.write("\t\t\t\t\t<p class=\"slidetxt\">IT STUDETNS WINDOW</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"mySlides2 fadeMsg\">\r\n");
      out.write("\t\t\t\t\t<img src=\"Image/wow.png\" alt=\"Popular\" width=\"150px\" height=\"150px\" class=\"pop\"/> \r\n");
      out.write("\t\t\t\t\t<p class=\"slidetxt\">WOW TRAVEL</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"mySlides2 fadeMsg\">\r\n");
      out.write("\t\t\t\t\t<img src=\"Image/private.png\" alt=\"Popular\" width=\"150px\" height=\"150px\" class=\"pop\"/> \r\n");
      out.write("\t\t\t\t\t<p class=\"slidetxt\">PRIVATE SCHOOL</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"mySlides2 fadeMsg\">\r\n");
      out.write("\t\t\t\t\t<img src=\"Image/babycare.png\" alt=\"Popular\" width=\"150px\" height=\"150px\" class=\"pop\"/> \r\n");
      out.write("\t\t\t\t\t<p class=\"slidetxt\">BABY CARE</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"mySlides2 fadeMsg\">\r\n");
      out.write("\t\t\t\t\t<img src=\"Image/logo.png\" alt=\"Popular\" width=\"150px\" height=\"150px\" class=\"pop\"/> \r\n");
      out.write("\t\t\t\t\t<p class=\"slidetxt\">IT STUDENT WINDOW</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"mySlides2 fadeMsg\">\r\n");
      out.write("\t\t\t\t\t<img src=\"Image/logo.png\" alt=\"Popular\" width=\"150px\" height=\"150px\" class=\"pop\"/> \r\n");
      out.write("\t\t\t\t\t<p>Slide 6</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"mySlides2 fadeMsg\">\r\n");
      out.write("\t\t\t\t\t<img src=\"Image/logo.png\" alt=\"Popular\" width=\"150px\" height=\"150px\" class=\"pop\"/> \r\n");
      out.write("\t\t\t\t\t<p>Slide 7</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<div class=\"Ads\">\r\n");
      out.write("\t\t\t\t<img src=\"Image/logo.png\" width=\"50px\" height=\"50px\" class=\"i\">\r\n");
      out.write("\t\t\t\t<img src=\"Image/logo.png\" width=\"50px\" height=\"50px\" class=\"i\">\r\n");
      out.write("\t\t\t\t<img src=\"Image/logo.png\" width=\"50px\" height=\"50px\" class=\"i\">\r\n");
      out.write("\t\t\t\t<p>IT STUDENTS WINDOW Ads</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"ads\">\r\n");
      out.write("\t\t\t\t<img src=\"Image/logo.png\" width=\"50px\" height=\"50px\" class=\"i\">\r\n");
      out.write("\t\t\t\t<img src=\"Image/logo.png\" width=\"50px\" height=\"50px\" class=\"i\">\r\n");
      out.write("\t\t\t\t<img src=\"Image/logo.png\" width=\"50px\" height=\"50px\" class=\"i\">\r\n");
      out.write("\t\t\t\t<p>IT STUDENTS WINDOW Ads</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("</div>\r\n");
      out.write("     <script type=\"text/javascript\" src=\"JS/slide.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"JS/background.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"JS/slidepop.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"JS/home.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t</body>\r\n");
      out.write("\t</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
